name: Build and Call Reusable Deploy

on:
  workflow_dispatch:

jobs:
  build-job:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.x'

      - name: Build Code
        run: dotnet build --configuration Release

      - name: Publish code
        run: dotnet publish -c Releas --property:PublishDir="${{env.DOTNET_ROOT}}\myapp"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          # Artifact name
          name: .net-app
          path: ${{env.DOTNET_ROOT}}\myapp

  call-reusable-deployment-workflow-job:
    needs: build-job

    uses: kishorecheryala09/shared-workflows/.github/workflows/reusable-deploy-shared-repo.yml@main
    with:
      package-name: .net-app
      app-name: appsvc1
      deployment-slot: development
    secrets:
      azure-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
    
  
